### ISSUE TITLE
Install via Zip does not work

### ISSUE THREAD

**Issue by bh** [runelaenen/sw6-media-optimizer#2]
Hi there,
I have SW 6.3.3.0 and installed your plugin via Zip upload (admin interface). When trying to use the command:

```bash
bin/console rl:media:optimize
```
it fails with the following exception:
```
In srcShopware_Production_KernelProdContainer.php line 16965:
                                                                                           
  Attempted to load class "OptimizerChainFactory" from namespace "Spatie\ImageOptimizer".  
  Did you forget a "use" statement for another namespace?         
```
Any idea to fix this?

**Comment by runelaenen** [comment]
Did you download the correct zip file? You can only use 'Releases' zips this way, and not the 'Download ZIP' function from GitHub.

Releases: https://github.com/runelaenen/sw6-media-optimizer/releases/tag/v1.0.0

**Comment by bh** [comment]
Yes, I used:
`wget https://github.com/runelaenen/sw6-media-optimizer/releases/download/v1.0.0/RuneLaenenMediaOptimizer.zip
`

**Comment by runelaenen** [comment]
Weird, the composer should be installed there. Anyway, you can run composer install in the plugin directory to fix the issue :)

**Comment by runelaenen** [comment]
Ah no, I see I forgot to add the autoloader to the plugin class.
You can either wait until I have some time to update the plugin, or install it via composer. That will also load the dependencies.

**Comment by bh** [comment]
I have no composer ready (I installed SW via installer.zip). Do you have patch so I can fix it in code directly? :dancers:

**Comment by runelaenen** [comment]
I've just pushed a new version, it should be available in a few minutes.

**Comment by bh** [comment]
Wow, thank you! <3

```
$ bin/console rl:media:optimize
   14/4110 [>---------------------------]   0%
```
